### PR TITLE
Issue 660 - Update XcodeProj dependency

### PR DESCRIPTION
**Pull request by geraldWilliam**
This updates the XcodeProj dependency to the latest version.

### CODE REVIEW

**Comment by geraldWilliam** [comment]
@ileitch I'm not sure how to troubleshoot the failing check. Any advice?

**Comment by gnrcampos** [comment]
I'd love to see this merged sooner rather than later, sorry I can't help with the checks

**Comment by geraldWilliam** [comment]
@gnrcampos Closing this PR because the latest `master` has 8.16.0 in Package.resolved.

**Comment by gnrcampos** [comment]
Thanks Gerald and @ileitch. Any idea when the new release is coming?

**Comment by ileitch** [comment]
Soon. I'm working through running Periphery on a large project and fixing a bunch of false-positives.

**Pull request closed without merging**
