### PR TITLE
Suport Swift5.1

### PR DESCRIPTION
**Pull request by kateinoigakukun**
- Update SwiftSyntax to support Swift5.1
  - Remove byte-tree related code because it's removed from swift-syntax
  - Fix compile error for new swift-syntax

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@ileitch Could you update Swift version on Bitrise?

**Comment by ileitch** [comment]
> @ileitch Could you update Swift version on Bitrise?

Done.

**Comment by kateinoigakukun** [comment]
@ileitch Sorry I forgot to specify the Xcode version, could you set Xcode version as 11.3.1?
Latest SwiftSyntax doesn't support Xcode 11.4.x.

**Comment by ileitch** [comment]
I've updated the Xcode version, but please also see this issue on the status of Periphery: https://github.com/peripheryapp/periphery/issues/66

**Pull request merged**
