### PR TITLE
Replace hashValue with Hashable.hash(into:)

### PR DESCRIPTION
**Pull request by freak4pc**
Hey there! Really exciting seeing this project come to open source. 🏆 

Wanted to push a tiny PR to switch from `hashValue` to `hash(into:)` as added in [Swift 4.2's SE-0206](https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md#hash-into).

### CODE REVIEW

**Comment by ileitch** [comment]
First PR! Thank you 😃 

Now I really need to get CI setup...

**Comment by freak4pc** [comment]
That could be the second PR ;-)

**Comment by ileitch** [comment]
Indeed. There's so many services to choose from these days, which is in vogue at the moment?

**Comment by freak4pc** [comment]
I guess Bitrise and Circle are the big two, in my view at least :)

**Comment by ileitch** [comment]
Here's an idea, a website that ranks CI services based on usage on github. I'm happy to go with the herd.

**Pull request merged**
