### PR TITLE
Xcode10.2

### PR DESCRIPTION
**Pull request by ileitch**

### CODE REVIEW

**Comment by Dschee** [comment]
Would be great to have this merged and a new release been made, now that Xcode 10.2 was released and people are switching to it. Can't use periphery as of now.

**Comment by ileitch** [comment]
There's still some work to do, and I believe a bunch of regressions I reported in the 10.2 betas were not fixed by Apple. I still need to investigate further.

**Comment by petaren** [comment]
When can we expect this branch to be ready and merged?

**Comment by ileitch** [comment]
Sorry for the delay, I should have some time this weekend.

**Comment by chrisballinger** [comment]
FWIW I was able to compile and run this branch for a project targeting Xcode 10.2 / Swift 5. 

I encountered a compilation/linker issue when using the Makefile in release mode, but building in release mode through the generated xcodeproj worked fine.

```
$ make build_release
...
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift_static/macosx'
ld: warning: Could not find auto-linked library 'swiftFoundation'
ld: warning: Could not find auto-linked library 'swiftDarwin'
ld: warning: Could not find auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find auto-linked library 'swiftIOKit'
ld: warning: Could not find auto-linked library 'swiftXPC'
ld: warning: Could not find auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find auto-linked library 'swiftCore'
ld: warning: Could not find auto-linked library 'swiftObjectiveC'
ld: warning: Could not find auto-linked library 'swiftDispatch'
ld: warning: Could not find auto-linked library 'swiftos'
Undefined symbols for architecture x86_64:
```

**Comment by Dschee** [comment]
Interesting, this looks very similar to [this issue](https://github.com/Flinesoft/BartyCrouch/issues/123) here I had in another project, while not being exactly the same. But it also appeared after upgrading to Xcode 10.2 / Swift 5, so apparently since Swift 5 is now ABI stable linking swifts own frameworks seems to have changed. I remember fixing the issue by simply not linking against any Swift 5 frameworks anymore, as they were somehow already available (in the OS?). Not sure if that info helps here though.

**Comment by kevin180git** [comment]
May I ask how you were about to compile and run this branch? Kind of struggling and want to test this out

**Comment by mackoj** [comment]
add this `Library Search Paths = $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` it will fix it

**Pull request merged**
