### PR TITLE
feat: Support filter by source branch

### PR DESCRIPTION
**Pull request by hoangatuan**
## Description

Currently, we don't support filter results only on changed/added files. This PR adds logic to support that feature.

## How it works?

1. Using periphery scan to get the outputs.
2. Use 'git diff $sourceBranch --path $filePath' to get all the changes in that file. (filePath comes from the output.declaration.location.path)
3. Compare the output.declaration.location.line with the newLineStart and newLineSpan from the diff. If it matches, then it's a new/changed line.

## Notes

This is a propose idea and solution. I haven't updated the tests. If you feel the feature and the solution is okay, I will update the tests. 
Please take a look and let me know if you have any suggestions. Thank you

### CODE REVIEW

**Comment by hoangatuan** [comment]
Hi @ileitch, I have a proposal here. It will be nice if you can take a look when you have time. Thank youu

**Comment by ileitch** [comment]
Hey @hoangatuan thanks for the PR, and sorry for the slow review.

This is indeed a useful feature, but if I understand your use case correctly, this can already be achieved using the baseline feature.

```
$ git checkout A
$ periphery scan --write-baseline branch_a_baseline
$ git checkout B
$ periphery scan --baseline branch_a_baseline
```

The scan on branch B will output all results, excluding those in branch A. Does that achieve what you want?

**Comment by hoangatuan** [comment]
@ileitch Let me take a look. However, I got this question:

After we switch to branch B and run periphery, do we need to build the project again (because we need to generate the DataStore again)?

**Comment by ileitch** [comment]
You should only need to build twice:

```
$ git checkout A
$ xcodebuild ...
$ periphery scan --skip-build --index-store-path ... --write-baseline A
$ git checkout B
$ periphery scan --baseline A
```

**Comment by ileitch** [comment]
I think you have two options:
1. Record the target branch baseline when a PR is merged and save it somewhere. When you run periphery in a feature branch, you use the associated baseline for the branch [merge-base](https://git-scm.com/docs/git-merge-base) commit.
2. Parse the results and perform the filtering outside of Periphery in a script.
3. Use `--report-exclude` to filter unchanged files.

I'm hesitant to merge this feature as-is for the following reasons:
1. It assumes Periphery is being run in a git repo.
2. Comparing changes based on file/line location can be inaccurate, e.g., when a function is moved but otherwise unchanged. The baselines use the IDs generated by the compiler and do not have this problem.
4. I'd prefer not to support multiple ways of achieving the same thing, and you already have a few different options as listed above.

Ultimately, I'd like to see more people asking for this feature before we implement it. Either way, I do appreciate you taking the time to contribute!

**Pull request closed without merging**
