### PR TITLE
Bazel support

### PR DESCRIPTION
**Pull request by ileitch**
Setup steps:
* Checkout this branch and build periphery with `make build_arm64`
* Add Periphery to your `MODULE.bazel`
```
bazel_dep(name = "periphery", version = "2.21.0")
git_override(
    module_name = "periphery",
    remote = "/path/to/periphery",
    commit = "<HEAD of bazel branch>"
)
```
* Add `@periphery//bazel:generated` to `package_group` includes as needed.
* Run periphery from your project: `~/path/to/periphery/.build/release/periphery scan --bazel --verbose`

TODO:
* [x] Plist collection not identifying all files.
* [x] Exit with Bazel status code.
* [x] ~Add OnlyCompile aspect?~
* [x] ~Add option to configure target expression~.
* [x] Add option to filter targets.
* [x] ~Vend the periphery binary in MODULE.bazel~
* [x] Make sure `BazelProjectDriver.kinds` is all we need.
* [x] ~Scope generated output directory by project?~
* [x] Exclude external deps from the query.
* [x] xib, datamodel support
* [x] ~Integrate Bazel support in CI~
* [x] Query can fail when server starts:
```
@@periphery~~generated~periphery_generated//rule:scan: invalid label '@@Starting local Bazel server and connecting to it...' in element 0 of attribute 'deps' in 'scan' rule: invalid repository name 'Starting local Bazel server and connecting to it...': repo names may contain only A-Z, a-z, 0-9, '-', '_', '.' and '~' and must not start with '~'
```

### CODE REVIEW

**Comment by tinder-maxwellelliott** [comment]
Should we also work to have Periphery building via Bazel to ensure its fully hermetic?

**Comment by maxwellE** [comment]
Should we also work to have Periphery building via Bazel to ensure its fully hermetic?

**Comment by ileitch** [comment]
Yes, I think that would be nice to have, and simplify including Peripheral in Bazel projects. I didn't  look into it yet though.

**Comment by ileitch** [comment]
@maxwellE I gave this a shot in the [bazel-swiftpm](https://github.com/peripheryapp/periphery/tree/bazel-swiftpm) branch using `rules_swift package_manager`, but I ran into a potential compatibility issue with Yams: https://github.com/cgrindel/rules_swift_package_manager/issues/1198.

**Pull request merged**
